services:
  frontend:
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost/s4s/api
      - NEXT_PUBLIC_FRONTEND_URL=https://localhost/s4s
    ports:
      - "3000:3000"

  backend:
    volumes:
      - ./backend:/app
      - ./data:/data
      - ./sockets:/sockets
      - /var/run/docker.sock:/var/run/docker.sock
    command: cargo watch -x run
