FROM rust:1.89

# Install system dependencies (needed for Rocket / crates)
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
