FROM rust:1.81-slim

# Install system dependencies (needed for Rocket / crates)
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
 && cargo install cargo-watch \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
